# Generated by Django 3.0.4 on 2020-09-26 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('open_hour_in_week_from', models.TimeField(default=datetime.time(9, 0))),
                ('open_hour_in_week_to', models.TimeField(default=datetime.time(7, 30))),
                ('open_hour_in_saturday_from', models.TimeField(default=datetime.time(9, 0))),
                ('open_hour_in_saturday_to', models.TimeField(default=datetime.time(6, 0))),
                ('open_hour_in_sunday_from', models.TimeField(default=datetime.time(9, 0))),
                ('open_hour_in_sunday_to', models.TimeField(default=datetime.time(5, 0))),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
